name: Test and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup node and generate static files
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm install standard rollup -g
    - run: npm test
    - name: Tests OK
      if: ${{ success() }}
      run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ github.token }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Test have passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
    - name: Deploy
      if: ${{ success() }}
      run: |
          mkdir docs
          cp -r dist/* docs/
          current_timestamp=`date +%s`
          sed -i "s/simct\.js/simct\.js?v=${current_timestamp}/g" docs/index.html
          rollup main.js --file docs/simct.js --format es
          npx standard docs/simct.js --fix
          cat app/view/css/*.css > docs/simct.css
          cd docs && zip -r ../simct.zip ./* && cd ..          
          mv simct.zip docs/
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add docs/*
          git diff-index --cached --quiet HEAD || git commit -m "Update simct.js" &&
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push origin main:gh-pages -f
    - name: Tests KO
      if: ${{ failure() }}
      run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests have failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
